[package]
name = "twitter-stream-message"
version = "0.3.0"
authors = ["Daiki Mizukami <tesaguriguma@gmail.com>"]
license = "MIT"
readme = "../README.md"
keywords = ["twitter"]
homepage = "https://github.com/tesaguri/twitter-stream-message"
repository = "https://github.com/tesaguri/twitter-stream-message"
documentation = "https://docs.rs/twitter-stream/0.3.0/twitter_stream-message/"
description = """
Types for Twitter Streaming API's messages.
"""

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
